### ISSUE TITLE
Mistake in detecting sloppy gestures

### ISSUE THREAD

**Issue by es-andreev** [Almeros/android-gesture-detectors#30]
It seems there is a mistake in calculating raw coordinates of motion events, please see TwoFingerGestureDetector.getRawX(MotionEvent, int) (line 122) and TwoFingerGestureDetector.getRawY(MotionEvent, int) (line 136).

You should actually calculate offset like 
`float offset = event.getRawX() - event.getX();`
and
`float offset = event.getRawY() - event.getY();`

**Comment by Almeros** [comment]
Please elaborate a bit more; Why is it wrong? This has never been a problem for others (at least till now) and myself . Are you sure the problem you have is originating here?

**Comment by es-andreev** [comment]
I faced a problem with rotation gestures, it didn't start in some cases. I started digging and found:
you do in TwoFingerGestureDetector.getRawX()
`float offset = event.getX() - event.getRawX();`
and then
`return event.getX(pointerIndex) + offset;`

Let's assume `pointerIndex` is 0. Then this method (TwoFingerGestureDetector.getRawX) should return the same value as calling event.getRawX(). But in your case it eventually returns event.getX() + event.getX() - event.getRawX(). Am I wrong?

**Comment by matteblair** [comment]
+1 On this report.

I use this repo in [Tangram ES](https://github.com/tangrams/tangram-es). A user recently reported an issue with rotate gestures and managed to specifically identify this same line as the source. I reproduced the issue in a test and verified that negating `offset` corrects the behavior.

I've used this code for a long time without noticing problems, so I was also very skeptical at first! This error doesn't cause problems if your View covers most or all of the display, because `offset` is approximately 0 in those cases. But as the previous comment adeptly explained, the algebraic logic of these lines is clearly not right.
